### ISSUE TITLE
Cannot print from photo tray

### ISSUE THREAD

**Issue by alexandreblin** [mobileprint/ios-print-sdk#2]
I am unable to print an image on photo paper when using the SDK.

When trying to print on photo paper, the printer tries to use paper from the regular paper tray instead of using the photo tray.

I use a brand new HP Envy 7640. Photo paper is correctly loaded inside the photo tray of the printer. Here are screenshots of the print settings:

<img src="https://cloud.githubusercontent.com/assets/1523191/14603739/c7b43ee8-056f-11e6-8c5a-5bf6d9366c8a.png" width="400"/>

(sorry, my device is in French, but it says 10x15cm photo paper which is the correct format)

However, using iOS native print, the printer uses paper from the photo tray as expected when using the Photo paper setting:
<img src="https://cloud.githubusercontent.com/assets/1523191/14603849/7b576998-0570-11e6-89de-edbd21f3f493.png" width="400"/>

What could be causing the problem? This is always reproducible. I'll gladly help you debug this if needed.

**Comment by chmurray** [comment]
Thanks for reporting this!  Sorry for the delayed response.  We're beginning to do our own troubleshooting on this today.  I'll let you know what we find.

**Comment by chmurray** [comment]
We're running a fix through our testing process now.

**Comment by chmurray** [comment]
We've published version 3.0.5 of the MobilePrintSDK with a fix for this issue.

**Comment by alexandreblin** [comment]
Thanks, this fixed the issue, I successfully printed a photo on 10x15cm photo paper 👍
