### ISSUE TITLE
Problems with Split View mode on iPad

### ISSUE THREAD

**Issue by alexandreblin** [mobileprint/ios-print-sdk#3]
Our app supports iOS 9 split view mode. But we have some problem when using the print SDK in our app when the app is in split view mode.

When we open the print view controller, we are directly on the Preview screen with no print or settings.
To actually print the photo, we need to press the Back button to go to the printing settings
<img src="https://cloud.githubusercontent.com/assets/1523191/14920081/0f56aea6-0e2c-11e6-8401-e6f5b246a241.png" width="700"/>

Second problem, when trying to select a printer, the printer selection view controller displays in full screen and pressing "Cancel" doesn't dismiss it.
<img src="https://cloud.githubusercontent.com/assets/1523191/14920169/845ecaf8-0e2c-11e6-96a6-fafbd40217f0.png" width="700"/>

Note that these problem do not occur on iPhone. Only on iPad when in split view mode.

**Comment by chmurray** [comment]
Thanks for reporting this issue!  We're working on a fix now.

**Comment by chmurray** [comment]
We just released version 3.0.6 of MobilePrintSDK.  Version 3.0.6 adds support for the split view.

**Comment by erictalle** [comment]
@alexandreblin were you able to try version 3.0.6 of MobilePrintSDK?  Let us know if there are any other issues related to this.

**Comment by erictalle** [comment]
@alexandreblin we'll close this issue.  If you still have issues with multitasking and split view please submit another issue.
